ALTER TABLE users
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS password_hash TEXT,
ADD COLUMN IF NOT EXISTS is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;

ALTER TABLE users
ALTER COLUMN address DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_lower
ON users (LOWER(email))
WHERE email IS NOT NULL;
